name: snapshot-hash

on:
  push:
    paths:
      - ".github/workflows/snapshot-hash.yml"
      - "go/snapshot-hash/**"
  workflow_dispatch:
    inputs:
      after:
        description: "after: Returns the elements in the list that come after the specified cursor"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 2
        uses: actions/setup-python@v2
        with:
          python-version: "2.7"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Get dependencies
        run: |
          cd go
          go get -v -t -d ./...

      - run: |
          cd go
          go run ./snapshot-hash
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AFTER: ${{ github.event.inputs.after }}

      - name: upload snapshot-hash.csv
        uses: actions/upload-artifact@v2
        with:
          name: snapshot-hash
          path: go/snapshot-hash.csv
